### ISSUE TITLE
directory not found - kodi Nexus

### ISSUE THREAD

**Issue by Isayso** [mking2203/plugin.video.deluxemusic#2]
again, the directory not found error in playmedia.

Thanks!

**Comment by mking2203** [comment]
Okay, the web site changed... I have to find out how to get the hls streaming working

**Comment by Isayso** [comment]
Again directory not found. V 3.0.2 on Libreelec 10.0.2   Thanks!

**Comment by mking2203** [comment]
Okay, now it's working again ;-)
